//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public string Id { get; set; }
        public string StudentId { get; set; }
        public string Crebo { get; set; }
        public string Slb { get; set; }
        public string Group { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
