//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        public string Id { get; set; }
        public string Code { get; set; }
        public int Wage { get; set; }
        public string Manager { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
